dns:
  enable: true
  listen: ':53'
  enhanced-mode: 'fake-ip'
  fake-ip-range: '198.18.0.1/16'
  fake-ip-range6: 'fdfe:dcba:9876::1/64'
  fake-ip-filter-mode: 'blacklist'
  prefer-h3: true
  respect-rules: true
  use-hosts: false
  use-system-hosts: false
  ipv6: false
  fake-ip-filter:
    - '+.lan'
    - '+.local'
    - '+.arpa'
    - 'localhost'
    - 'localhost.localdomain'
    - 'time.*.com'
    - 'ntp.*.com'
    - '+.pool.ntp.org'
  default-nameserver:
    - 'https://223.5.5.5/dns-query#DIRECT'
    - 'https://223.6.6.6/dns-query#DIRECT'
  nameserver:
    - 'https://1.1.1.1/dns-query#RULES'
    - 'https://8.8.8.8/dns-query#RULES'
  direct-nameserver-follow-policy: false
  fallback-filter:
    geoip: true
    geoip-code: 'CN'
    ipcidr:
      - '240.0.0.0/4'
      - '0.0.0.0/32'
      - '127.0.0.1/32'
      - '100.64.0.0/10'
    domain: []
  fallback:
    - 'https://1.1.1.1/dns-query#RULES'
    - 'https://8.8.8.8/dns-query#RULES'
  proxy-server-nameserver:
    - 'https://223.5.5.5/dns-query#DIRECT'
    - 'https://223.6.6.6/dns-query#DIRECT'
  direct-nameserver:
    - 'https://223.5.5.5/dns-query#DIRECT'
    - 'https://223.6.6.6/dns-query#DIRECT'
  nameserver-policy:
    geosite:gfw:
      - 'https://1.1.1.1/dns-query#RULES'
      - 'https://8.8.8.8/dns-query#RULES'
